import { Inter } from "next/font/google";
import "./globals.css";
import CustomNavBar from "@/components/customnavbar";
import Footer from "@/components/footer";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
import UserProvider from "@/context/userprovider";
import UserContext from "@/context/usercontext";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <UserProvider>
       <ToastContainer/>
        <CustomNavBar />
        <div className="mt-2">{children}</div>
        <Footer />
       </UserProvider>
      </body>
    </html>
  );
}
